#!/usr/bin/env python3

# -*- coding: UTF-8 -*-
#

# generated by wxGlade 1.1.0 on Mon Nov 25 15:16:13 2024
#


import wx


class CommandBox(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CommandBox.__init__

        kwds["style"] = kwds.get("style", 0) | wx.FRAME_NO_TASKBAR | wx.STAY_ON_TOP

        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("frame")


        self.CommandText = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.BORDER_NONE | wx.TE_NO_VSCROLL | wx.TE_PROCESS_ENTER | wx.TE_PROCESS_TAB)

        self.Layout()
        self.Centre()

        # end wxGlade


# end of class CommandBox